master/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('student.urls')),
    path('admin/', admin.site.urls),
]

student/urls.py
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
    # Index Page
    path('', views.index, name='index'),

    # Instructor Page
    path('instructor/', views.InstructorIndexView.as_view(), name='instructor'),

    # Student Pages
    path('student/', views.StudentIndexView.as_view(), name='student'),
    #path('student/add', views.StudentCreate.as_view(), name="student-add"),
    path('student/add', views.student_create, name="student-add"),
    path('student/update/<pk>', views.StudentUpdate.as_view(), name="student-update"),
    path('student/delete/<pk>', views.StudentDelete.as_view(), name="student-delete"),
    path('student/<pk>', views.studentdetail, name='detail'),
    path('student/<pk>/guardian', views.GuardianCreate.as_view(), name='student-guardian'),

    # Enrollment Pages
    path('enroll/', views.EnrollIndexView.as_view(), name='enroll'),
    path('enroll/add', views.EnrollCreate.as_view(), name="enroll-add"),
    path('enroll/update/<pk>', views.EnrollUpdate.as_view(), name="enroll-update"),
    path('enroll/delete/<pk>', views.EnrollDelete.as_view(), name="enroll-delete"),

    # Batch Pages
    path('batch/', views.BatchIndexView.as_view(), name='batch'),
    path('batch/<pk>/students', views.batchstudent, name='batch_student'),
    path('batch/add', views.BatchCreate.as_view(), name='batch-add'),
    path('batch/update/<pk>', views.BatchUpdate.as_view(), name='batch-update'),
    path('batch/delete/<pk>', views.BatchDelete.as_view(), name='batch-delete'),

    # Attendance Pages
    path('attend/', views.AttendanceIndexView.as_view(), name='attend'),
    path('attend/add', views.AttendanceCreate.as_view(), name='attend-add'),
    path('attend/update/<pk>', views.AttendanceUpdate.as_view(), name='attend-update'),
    path('attend/delete/<pk>', views.AttendanceDelete.as_view(), name='attend-delete'),

    # Finance Pages
    path('finance/', views.FinanceIndexView.as_view(), name='finance'),
    path('finance/add', views.FinanceCreate.as_view(), name='finance-add'),
    path('finance/update/<pk>', views.FinanceUpdate.as_view(), name='finance-update'),
    path('finance/delete/<pk>', views.FinanceDelete.as_view(), name='finance-delete'),

    # Report Page
    path('report/', views.monthly_report, name='report'),

    # Progess Page
    path('progress/add/<pk>', views.progress_add, name="progress"),

    # Search Pages
    path('studentsearch/', views.student_search, name="student-search"),
    path('enrollsearch/', views.enroll_search, name="enroll-search"),
    path('attendancesearch/', views.attendance_search, name="attend-search"),
    path('financesearch/', views.finance_search, name="finance-search"),
]

student/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from .models import Instructor, Student, Attendance, Progress, Fee, Batch, Enrollment, Guardian
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.db.models import Q
from functools import reduce

from datetime import datetime
from django.db.models import Sum

from .form import *

# Index Page
def index(request):
    instructor = Instructor.objects.get(id=1)
    return render(request, 'student/index.html', context={'instructor': instructor})

# Instructor Page
class InstructorIndexView(generic.ListView):
    template_name = 'student/instructor.html'

    def get_queryset(self):
        return Instructor.objects.all()
        
# Student Index Page
class StudentIndexView(generic.ListView):
    template_name = 'student/student.html'

    def get_queryset(self):
        return Student.objects.all()

# Student Detail Page
def studentdetail(request, pk):
    student_detail = Student.objects.get(pk=pk)
    guardian_detail = student_detail.guardian
    attendance_detail = Attendance.objects.filter(student=pk)
    progress_detail = Progress.objects.filter(student=pk)
    fee_detail = Fee.objects.filter(student=pk)
    context = {
        'stu': student_detail,
        'guardian': guardian_detail,
        'attendance': attendance_detail,
        'progress':  progress_detail,
        'fee': fee_detail,
    }
    return render(request, 'student/detail.html', context)

# Student Update Pages
# class StudentCreate(CreateView):
#     model = Student
#     fields = ['first_name', 'last_name', 'address', 'city', 'date_of_birth', 'date_of_joining', 'phone_number', 'rank',
#               'guardian']

def student_create(request):
    if request.POST:
        stu_form = StudentForm(request.POST or None, prefix="student")
        en_form = EnrollmentForm(request.POST or None)
        guardian_form = GuardianForm(request.POST or None, prefix="guardian")
        if stu_form.is_valid() and en_form.is_valid() and guardian_form.is_valid():
            if guardian_form.has_changed():
                guardian = guardian_form.save()
                student = stu_form.save(commit=False)
                student.guardian = guardian
            student = stu_form.save(commit=False)
            stu_form.save()
            progress = Progress.objects.create(progress_belt_to=student.rank, student=student)
            progress.save()
            enrollment = en_form.save(commit=False)
            enrollment.student = student
            en_form.save()
            stu = Student.objects.all()
            return render(request, 'student/student.html', {'object_list': stu})
    else:
        stu_form = StudentForm(request.POST or None, prefix="student")
        en_form = EnrollmentForm(request.POST or None)
        guardian_form = GuardianForm(request.POST or None, prefix="guardian")
        return render(request, 'student/student_form.html', {"form": stu_form, "form1": en_form, "form2": guardian_form})

class StudentUpdate(UpdateView):
    model = Student
    fields = ['first_name', 'last_name', 'street_name', 'city', 'province', 'postal_code', 'date_of_birth', 'date_of_joining', 'phone_number', 'rank',]

class StudentDelete(DeleteView):
    model = Student
    success_url = reverse_lazy('student:student')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

def student_search(request):
    template = 'student/student.html'

    query = request.GET.get('q')

    results = Student.objects.filter(Q(pk__icontains=query) |
                                     Q(first_name__icontains=query) |
                                     Q(last_name__icontains=query) |
                                     Q(guardian__first_name__icontains=query) |
                                     Q(guardian__last_name__icontains=query))

    context = {
        'object_list': results
    }

    return render(request, template, context)

# Enrollments
class EnrollIndexView(generic.ListView):
    template_name = 'student/enroll.html'

    def get_queryset(self):
        return Enrollment.objects.all()

class EnrollCreate(CreateView):
    model = Enrollment
    fields = ['student', 'batch']

class EnrollUpdate(UpdateView):
    model = Enrollment
    fields = ['student', 'batch']

class EnrollDelete(DeleteView):
    model = Enrollment
    success_url = reverse_lazy('student:enroll')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

def enroll_search(request):
    template = 'student/enroll.html'

    query = request.GET.get('q')

    results = Enrollment.objects.filter(Q(batch__batch_day__icontains=query) |
                                        Q(student__first_name__icontains=query) |
                                        Q(student__last_name__icontains=query) |
                                        Q(batch__level__level_name__icontains=query))

    context = {
        'object_list': results
    }

    return render(request, template, context)

def guardian_create(request, pk):
    if request.POST:
        guardian_form = GuardianForm(request.POST or None, prefix="guardian")
        student = Student.objects.get(pk=pk)
        if guardian_form.is_valid():
            guardian = guardian_form.save()
            student.guardian = guardian
            student.save(force_update=True)
            stu = Student.objects.get(pk=pk)
            return render(request, 'student/student.html', {"object_list": stu})
    else:
        guardian_form = GuardianForm(request.POST or None, prefix="guardian")
        return render(request, 'student/student_form.html', {"form": guardian_form})

def progress_add(request, pk):
    if request.POST:
        progress_form = ProgressForm(request.POST or None, prefix="progress")
        student = Student.objects.get(pk=pk)
        if progress_form.is_valid():
            progress = progress_form.save(commit=False)
            progress.student = student
            student.rank = progress.progress_belt_to
            progress.save()
            student.save(force_update=True)
            stu = Student.objects.all()
            return render(request, 'student/student.html', {"object_list": stu})
            #return reverse('student:detail', args=[pk])
    else:
        progress_form = ProgressForm(request.POST or None, prefix="progress")
        return render(request, 'student/progress_form.html', {"form": progress_form})


class GuardianCreate(CreateView):
    model = Guardian
    fields = ['first_name', 'last_name', 'street_name', 'city', 'province', 'postal_code', 'phone_number', 'relation']

#Batch Information Pages
class BatchIndexView(generic.ListView):
    template_name = 'student/batch.html'

    def get_queryset(self):
        return Batch.objects.all()

class BatchCreate(CreateView):
    model = Batch
    fields = ['batch_day', 'batch_start_time', 'batch_end_time', 'level', 'instructor']

class BatchUpdate(UpdateView):
    model = Batch
    fields = ['batch_day', 'batch_start_time', 'batch_end_time', 'level', 'instructor']

class BatchDelete(DeleteView):
    model = Batch
    success_url = reverse_lazy('student:batch')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

# Students in given Batch
def batchstudent(request, pk):
    enrolls = Enrollment.objects.filter(batch=pk)
    students = []
    for enroll in enrolls:
        students.append(enroll.student)
    return render(request, 'student/student.html', { 'object_list': students })

# Attendance Page
class AttendanceIndexView(generic.ListView):
    template_name = 'student/attend.html'

    def get_queryset(self):
        return Attendance.objects.all()

class AttendanceCreate(CreateView):
    model = Attendance
    fields = ['student', 'attendance_date', 'attendance_count']

class AttendanceUpdate(UpdateView):
    model = Attendance
    fields = ['student', 'attendance_date', 'attendance_count']

class AttendanceDelete(DeleteView):
    model = Attendance
    success_url = reverse_lazy('student:attend')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

def attendance_search(request):
    template = 'student/attend.html'

    query = request.GET.get('q')

    results = Attendance.objects.filter(Q(attendance_date__icontains=query) |
                                        Q(student__first_name__icontains=query) |
                                        Q(student__last_name__icontains=query))

    context = {
        'object_list': results
    }

    return render(request, template, context)

# Finance Page
class FinanceIndexView(generic.ListView):
    template_name = 'student/finance.html'

    def get_queryset(self):
        return Fee.objects.all()

class FinanceCreate(CreateView):
    model = Fee
    fields = ['fee_name', 'fee_date', 'fee_amount', 'student']

class FinanceUpdate(UpdateView):
    model = Fee
    fields = ['fee_name', 'fee_date', 'fee_amount']

class FinanceDelete(DeleteView):
    model = Fee
    success_url = reverse_lazy('student:finance')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

def monthly_report(request):

    query = """SELECT 1 as id,  
                CASE strftime('%m',fee_date) WHEN '01' then 'January' 
                                            when '02' then 'Febuary' 
                                            when '03' then 'March' 
                                            when '04' then 'April' 
                                            when '05' then 'May' 
                                            when '06' then 'June' 
                                            when '07' then 'July' 
                                            when '08' then 'August' 

student/templates/student/attendance_form.html
{% extends 'student/base.html' %}

{% load staticfiles%}

{% block title %}Add Attendance{% endblock %}
{% block activeattend %}active{% endblock %}

{% block css %}
    <style>
        label {
            font-weight: bold;
        }
    </style>
{%endblock %}

{% block javascript%}
    <script>
        function addClasses() {
            let allInputs = $("input");
            allInputs.map(function (index, el) {
                    let element = document.getElementById(el.id);
                    if (element) {
                        document.getElementById(el.id).className = 'form-control';
                    }
                }
            );
            let selectTags = $("select");
            selectTags.map((index, el) => document.getElementById(el.id).className = 'form-control');
        }
        addClasses();
    </script>
{%endblock%}

{% block body %}
<div class="container-fluid bg-light" style="margin-top:24px;margin-bottom: 12px">
    <div class="row justify-content-center">
        <div class="col-md-6 col-md-offset-2">
            <div class="card">
                <div class="card-body">
                    <h3>Add New Attendance</h3>
                    <hr>
                    <div class="form-group" style="margin-top:24px">
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'student/form_template.html' %}
                            <div class="form-group">
                                <div class="text-center">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

student/templates/student/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
        crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
        crossorigin="anonymous"> {% block css %}{% endblock %}


    <title>{% block title %} Xia School of Martial Arts{% endblock %}</title>
</head>

<body class="bg-light">
    <!--Navigation-->
    <nav class="navbar navbar-dark bg-dark navbar-expand-sm m-0">
        <div class="container-fluid">
            <a class="navbar-brand text-light" href="{% url 'student:index' %}">Xia School of Martial Arts</a>
            <div class="navbar-nav">
                <a class="nav-item nav-link {% block activeinstructor %}{% endblock %}" href="{% url 'student:instructor' %}">Instructor</a>
                <a class="nav-item nav-link {% block activestudent %}{% endblock %}" href="{% url 'student:student' %}">Student</a>
                <a class="nav-item nav-link {% block activeenroll %}{% endblock %}" href="{% url 'student:enroll' %}">Enrollments</a>
                <a class="nav-item nav-link {% block activebatches %}{% endblock %}" href="{% url 'student:batch' %}">Batches</a>
                <a class="nav-item nav-link {% block activeattend %}{% endblock %}" href="{% url 'student:attend' %}">Attendance</a>
                <a class="nav-item nav-link {% block activefinance %}{% endblock %}" href="{% url 'student:finance' %}">Finance</a>
            </div>
        </div>
    </nav>

    <div>
    {% block body %} {% endblock %}
    </div>
    <footer class="page-footer font-small bg-dark fixed-bottom" style="height: 60px">
        <div class="footer-copyright text-center py-3 text-white">
            © Copyright by Tarang, Harita and Jenith
        </div>
    </footer>

    <!-- Optional JavaScript -->

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
{% block javascript %}{% endblock %}
</body>

</html>

student/templates/student/batch_form.html
{% extends 'student/base.html' %}

{% load staticfiles%}

{% block title %}Add Batch{% endblock %}
{% block activebatches %}active{% endblock %}

{% block css %}
    <style>
        label {
            font-weight: bold;
        }
    </style>
{%endblock %}

{% block javascript%}
    <script>
        function addClasses() {
            let allInputs = $("input");
            allInputs.map(function (index, el) {
                    let element = document.getElementById(el.id);
                    if (element) {
                        document.getElementById(el.id).className = 'form-control';
                    }
                }
            );
            let selectTags = $("select");
            selectTags.map((index, el) => document.getElementById(el.id).className = 'form-control');
        }
        addClasses();
    </script>
{%endblock%}

{% block body %}
<div class="container-fluid bg-light" style="margin-top:24px;margin-bottom: 12px">
    <div class="row justify-content-center">
        <div class="col-md-6 col-md-offset-2">
            <div class="card">
                <div class="card-body">
                    <h3>Add New Batch</h3>
                    <hr>
                    <div class="form-group" style="margin-top:24px">
                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'student/form_template.html' %}
                            <div class="form-group">
                                <div class="text-center">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

student/templates/student/detail.html
{% extends 'student/base.html' %}

{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="{% static 'student\detail.css' %}">
{% endblock %}

{% block javascript %}
<script src="{% static 'js\smoothScroll.js' %}"></script>
{% endblock %}

{% block title%}{{ stu }}{% endblock %}

{% block activestudent %}active{% endblock %}

{% block body %}
	<div class="container-fluid" style="padding-bottom: 100px;">
		<div class="m-4">
			<h1>{{ stu }}</h1>
		</div>
        <hr>
		<div class="row margin-top-20">
			<!--<div class="col-md-2">-->
				<!--<ul class="side-menu-items">-->
					<!--<li class="sliding-u-l-r-l">-->
						<!--<a href="#Information">General Information</a>-->
					<!--</li>-->
					<!--<li class="sliding-u-l-r-l">-->
						<!--<a href="#Contact">Emergency Contact</a>-->
					<!--</li>-->
					<!--<li class="sliding-u-l-r-l">-->
						<!--<a href="#Attendance">Attendance</a>-->
					<!--</li>-->
					<!--<li class="sliding-u-l-r-l">-->
						<!--<a href="#Progress">Progress</a>-->
					<!--</li>-->
					<!--<li class="sliding-u-l-r-l">-->
						<!--<a href="#Fees">Fees</a>-->
					<!--</li>-->
				<!--</ul>-->
			<!--</div>-->
			<div class="col-md-12">
				<div class="row">
					<div class="col-md-6" id="Information">
						<div class="card">
							<div class="card-header">
								<i class="fas fa-address-card"></i>
								General Information
							</div>
							<div class="card-body">
								<ul class="list-group list-group-flush">
									<li class="list-group-item">
										<span style="font-weight:bold">Address</span>: {{ stu.address }}</li>
									<li class="list-group-item">
										<span style="font-weight:bold">Postal Code</span>: {{ stu.postal_code }}</li>
									</li>
									<li class="list-group-item">
										<span style="font-weight:bold">Date of Birth</span>: {{ stu.date_of_birth }}</li>
									</li>
									<li class="list-group-item">
										<span style="font-weight:bold">Date of Joining</span>: {{ stu.date_of_joining }}</li>
									</li>
									<li class="list-group-item">
										<span style="font-weight:bold">Phone Number</span>: {{ stu.phone_number }}</li>
									</li>
									<li class="list-group-item">
										<span style="font-weight:bold">Rank</span>: {{ stu.rank }}</li>
									</li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-md-6" id="Contact">
						<div class="card">
							<div class="card-header">
								<i class="fas fa-address-card"></i>
								Emergency Contact
							</div>
							<div class="card-body">
								{% if guardian %}
								<ul class="list-group list-group-flush">
									<li class="list-group-item">
										<span style="font-weight:bold">Name</span>: {{ guardian }}</li>
									<li class="list-group-item">
										<span style="font-weight:bold">Address</span>: {{ guardian.address }}</li>
									</li>
									<li class="list-group-item">
										<span style="font-weight:bold">Postal Code</span>: {{ guardian.postal_code }}</li>
									</li>
									<li class="list-group-item">
										<span style="font-weight:bold">Phone Number</span>: {{ guardian.phone_number }}</li>
									</li>
									<li class="list-group-item">
										<span style="font-weight:bold">Relation</span>: {{ guardian.relation }}</li>
									</li>
								</ul>
								{% else %}
								<p> There is no Emergency Contact Added. Please <a href="{% url 'student:student-guardian' stu.pk %}">Cick here</a> to add </p>
								{% endif %}
							</div>
						</div>
					</div>
                    <hr>
					<div class="col-md-6 margin-top-20" id="Progress">
						<div class="card">
							<div class="card-header">
								<i class="fas fa-tasks"></i>
								Progress
                                <a class="btn float-right click" style="display:'inline-block'" href="{% url 'student:progress' stu.pk %}" role="button">
                                        <i class="fa fa-plus"></i>
                                    </a>
							</div>
							<div class="card-body">
								<table class="table table-responsive-sm table-striped table-condensed sortable">
									{% if progress %}
									<thead>
										<tr>
											<th align="center">From Belt</th>
											<th align="center">To Belt</th>
											<th align="center">Date</th>
										</tr>

									</thead>
									<tbody>
										{% for pro in progress %}
										<tr>
											<td>{{ pro.progress_belt_from }}</td>
											<td>{{ pro.progress_belt_to }}</td>
											<td>{{ pro.progress_date }}</td>
										</tr>
										{% endfor %}
									</tbody>
									{% else %}
									<p> There is no Progress Report Added. Please <a href="#">Cick here</a> to add </p>
									{% endif%}
								</table>
							</div>
						</div>
					</div>
					<div class="col-md-6 margin-top-20" id="Fees">
						<div class="card">
							<div class="card-header">
								<i class="fas fa-money-check-alt"></i>
								Fees
							</div>
							<div class="card-body">
								<table class="table table-responsive-sm table-striped table-condensed sortable">
									{% if fee %}
									<thead>
										<tr>
											<th align="center">Payment Type</th>
											<th align="center">Payment Date</th>
											<th align="center">Payment Amount</th>
										</tr>
									</thead>
									<tbody>
										{% for f in fee %}
										<tr>
											<td>{{ f.fee_name }}</td>
											<td>{{ f.fee_date }}</td>
											<td>{{ f.fee_amount }}</td>
										</tr>
										{% endfor %}
									</tbody>
									{% else %}
									<p> There is no Fees Added. Please <a href="{% url 'student:finance' %}">Cick here</a> to add </p>
									{% endif%}
								</table>
							</div>
						</div>
					</div>
                    <hr>
					<div class="col-md-12 margin-top-20" id="Attendance">
						<div class="card">
							<div class="card-header">
								<i class="fas fa-calendar-alt"></i>
								Attendance
							</div>
							<div class="card-body">
								<table class="table table-responsive-sm table-striped table-condensed sortable">
									{% if attendance %}
									<thead>
										<tr>
											<th align="center">Date</th>
											<th align="center">Count</th>
										</tr>
									</thead>
									<tbody>
										{% for attend in attendance %}
										<tr>
											<td>{{ attend.attendance_date }}</td>
											<td>{{ attend.attendance_count }}</td>
										</tr>
										{% endfor %}
									</tbody>
									{% else %}
									<p> There is no Attendance Added. Please <a href="{% url 'student:attend' %}">Cick here</a> to add </p>
									{% endif%}
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
    </div>
{% endblock %}

student/templates/student/enroll.html
{% extends 'student/base.html' %}

{% load staticfiles%}

{% block css %}
<link rel="stylesheet" href="{% static 'student\student.css' %}">
{% endblock %}

{% block javascript %}
<script src="{% static 'student/student.js' %}"></script>
{% endblock %}
{% block title%}Enrollments{% endblock %}
{% block activeenroll %}active{% endblock %}

{% block body %}
<div class="jumbotron bg-light">
    <div class="row">
        <div class="col col-lg-12">
            <a class="btn btn-dark" href="{% url 'student:enroll-add' %}" role="button">Add Enrollment</a>
            <div class="form-group float-right">
                <form action="{% url 'student:enroll-search' %}" method="GET" accept-charset="utf-8">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <i class="fa fa-search input-group-text" style="padding-top:10px;"></i>
                        </div>
                        <input
                                class="form-control"
                                type="text" name="q"
                                value="{{request.GET.q}}"
                                placeholder="Student or Batch"
                                style="width:500px;"/>
                    </div>
                </form>
            </div>
            <div style="margin-top:1em" class="card">
                <div class="card-header text-dark table-heading">Enrollments</div>
                <div class="card-body panel-full">
                    <table class="table table-responsive-sm table-striped table-condensed sortable">
                        <thead>
                            <tr class="text-center">
                                <th align="center">Student</th>
                                <th align="center">Batch</th>
                                 <th align="center">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for enroll in object_list %}
                            <tr class="text-center">
                                <td>{{ enroll.student }}</td>
                                <td>{{ enroll.batch }}</td>
                                <td style="padding: 0px">
                                    <a class="btn btn-info click" style="display:'inline-block'" href="{% url 'student:enroll-update' enroll.id %}" role="button">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <a class="btn btn-danger click" href="{% url 'student:enroll-delete' enroll.id %}" role="button">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

student/templates/student/finance_form.html
{% extends 'student/base.html' %}

{% load staticfiles%}

{% block title %}Add Student{% endblock %}
{% block activestudent %}active{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'student\student_form.css' %}">
{% endblock %}


{% block body %}
<div class="container-fluid bg-light">

    <div class="row justify-content-center">

        <div class="col-sm-12 col-md-7 ">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Batch</h3>
                    <div class="form-group">
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'student/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}